server:
  port: 8082
  servlet:
    context-path: /edu


spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  datasource:
#    url: jdbc:mysql://134.175.93.141:3306/ea?useUnicode=true&characterEncoding=utf8
#    username: root
#    password: admin123456
    url: jdbc:mysql://127.0.0.1:3306/ea?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

#  cache:
#    redis:
#      time-to-live: 60s
#    type: redis
#  redis:
#    host: 134.175.93.141
#    port: 6379
#    timeout: 10000
#    lettuce:
#      pool:
#        max-idle: 10
#        max-active: 10
#        min-idle: 5
#        max-wait: 10000
#    database: 0


  freemarker:
    suffix: .ftl
    content-type: text/html
    charset: UTF-8
    cache: false
    template-loader-path: classpath:/templates

shiro:
  loginUrl: /login
  unauthorizedUrl: /error/403.html
  successUrl: /
  sessionManager:
    sessionIdUrlRewritingEnabled: false

logging:
  level:
    com.blg.edu.mapper: debug
mybatis:
  configuration:
    map-underscore-to-camel-case: true
